name: inci_kuruyemis
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  #Navigation-Router
  auto_route: ^7.4.0

  #Responsive Design
  flutter_screenutil: ^5.8.4

  #SVG Package
  flutter_svg: ^2.0.7
  
  #Fonts
  google_fonts: ^5.0.0

  #Page Indicator
  smooth_page_indicator: ^1.1.0

  #Splash
  flutter_native_splash: ^2.3.1

  #Icons
  cupertino_icons: ^1.0.2

  #Sms Validation Field
  pinput: ^2.2.31

dev_dependencies:
  flutter_test:
    sdk: flutter

  #Navigation-Router
  auto_route_generator: ^7.1.1

  #Build
  build_runner: ^2.4.5

#Splash
flutter_native_splash:
  color: "#FFD200"
  image: assets/randomImage/real_pizza.jpg
  android: true   
  ios: true
  web: false

  #Linter
  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/
    - assets/randomImage/



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
