name: inci_kuruyemis
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  #Navigation-Router
  auto_route: ^7.4.0

  #Responsive Design
  flutter_screenutil: ^5.8.4

  #SVG Package
  flutter_svg: ^2.0.9
  
  #Fonts
  google_fonts: ^6.1.0

  #Page Indicator
  smooth_page_indicator: ^1.1.0

  #Splash
  flutter_native_splash: ^2.3.1

  #Icons
  cupertino_icons: ^1.0.2

  #Sms Validation Field
  pinput: ^2.2.31

  #State Management
  provider: ^6.1.1

  #Network Manager
  dio: ^5.4.1

  #Cache Manager
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0

  #Cookie Manager
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  path_provider: ^2.1.2

  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  #Navigation-Router
  auto_route_generator: ^7.1.1

  #Build
  build_runner: ^2.4.5

  #Launcher Icon
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/png/launcher_icon.png"
  apaptive_icon_background: "#FFD200"
  adaptive_icon_foreground: "assets/png/logo_foreground.png"


#Splash
flutter_native_splash:
  color: "#FFD200"
  image: assets/randomImage/real_pizza.jpg
  android: true   
  ios: true
  web: false

  #Linter
  very_good_analysis: ^5.1.0

flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/
    - assets/randomImage/

